SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[Date_YearBegin] (@contextDate DATETIME)
RETURNS DATETIME
AS
BEGIN
	RETURN  DATEADD(yy, DATEDIFF(yy, 0, @contextDate), 0)
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
