SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[Date_QuarterEnd](@contextDate DATETIME)
RETURNS DATETIME AS
BEGIN
	RETURN dbo.Date_DayEnd(DATEADD(qq, DATEDIFF(qq, -1, @contextDate),-1)) 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
