SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[Date_MonthBegin](@contextDate DATETIME)
RETURNS DATETIME AS
BEGIN
	RETURN DATEADD(mm, DATEDIFF(mm, 0, @contextDate),0) 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
