SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[Date_DayEnd](@contextDate DATETIME)
RETURNS DATETIME AS
BEGIN
	RETURN CAST(FLOOR(CAST(@contextDate AS DECIMAL(12, 5))) + 0.9999999999 AS DATETIME) 
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
