SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION GetMonthBeginDate (@date DATETIME)  
RETURNS DATETIME AS  
BEGIN
	RETURN CAST(CONVERT(VARCHAR(15), DATEADD(DAY, (DATEPART(DAY, @date)-1) * -1, @date), 101) AS DATETIME)
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
