CREATE TABLE [dbo].[_dba9348_PageCriterion] (
   [objectId] [int] NOT NULL
      IDENTITY (1,1),
   [allowChanges] [bit] NULL,
   [numericValue] [float] NULL,
   [textValue] [varchar](150) NULL,
   [timeValue] [datetime] NULL,
   [booleanValue] [bit] NULL,
   [dateRangeUnit] [int] NULL,
   [dateRangeOffset] [int] NULL,
   [operatorType] [int] NULL,
   [promptObjectId] [int] NULL,
   [version] [int] NOT NULL,
   [dataFieldObjectId] [int] NULL,
   [criterionType] [int] NOT NULL,
   [includeAll] [bit] NULL,
   [periodObjectId] [int] NULL,
   [singleSelect] [bit] NULL,
   [periodEditType] [int] NULL,
   [labelObjectId] [int] NOT NULL,
   [locationCategoryObjectId] [int] NULL,
   [enabledInclusionType] [int] NULL,
   [optimizable] [bit] NOT NULL,
   [relativePeriodTypeObjectId] [int] NULL,
   [relativePeriodCount] [smallint] NULL,
   [relativePeriodOffset] [smallint] NULL,
   [relativeSubPeriodTypeObjectId] [int] NULL,
   [dateSelectionType] [int] NULL,
   [relativeDisplayOption] [smallint] NULL,
   [inclusionType] [int] NULL,
   [attributeGroupObjectId] [int] NULL,
   [locationCategoryTypeObjectId] [int] NULL,
   [parentDataFieldObjectId] [int] NULL,
   [dateRangeRenderingType] [int] NULL,
   [dateListPickerMode] [bit] NULL,
   [pearModelObjectId] [int] NULL,
   [relativeSubTotalPeriodTypeObjectId] [int] NULL,
   [dynamicUnitSelectionType] [int] NULL,
   [periodTypeHierarchyObjectId] [int] NULL,
   [topLevelCount] [int] NULL
)


GO
