CREATE TABLE [dbo].[_gatwaydupe] (
   [objectId] [int] NOT NULL
      IDENTITY (1,1),
   [name] [varchar](50) NOT NULL,
   [description] [varchar](50) NULL,
   [dnis] [varchar](15) NULL,
   [failurePromptObjectId] [int] NULL,
   [audioOptionObjectId] [int] NULL,
   [version] [int] NOT NULL,
   [gatewayType] [int] NOT NULL,
   [alias] [varchar](25) NULL,
   [defaultOfferCodeObjectId] [int] NULL,
   [organizationObjectId] [int] NULL,
   [disabledLocationSurveyObjectId] [int] NULL,
   [appType] [int] NOT NULL,
   [customUrl] [varchar](250) NULL,
   [webSurveyStyleObjectId] [int] NULL,
   [locale] [varchar](25) NULL,
   [trimOfferCodeLeadingZeros] [bit] NOT NULL,
   [campaignObjectId] [int] NULL,
   [usingDnisPool] [bit] NULL,
   [persister] [int] NULL,
   [smsKeyword] [varchar](20) NULL,
   [contestRulesConfigObjectId] [int] NULL,
   [webSurveyPresentationOption] [int] NULL,
   [webSurveyThemeObjectId] [int] NULL,
   [allowIndexing] [bit] NULL,
   [disableDigitalFingerprint] [bit] NULL,
   [attemptLocationLookup] [bit] NULL,
   [vanityUrl] [varchar](250) NULL,
   [extendSurveyTimeout] [bit] NULL,
   [forceHttpsOnVanityUrl] [bit] NULL,
   [refreshInterval] [int] NULL,
   [disableInflightSurveyCheck] [bit] NULL,
   [enableRecaptcha] [bit] NULL,
   [captchaType] [int] NULL,
   [inboundEnabled] [bit] NULL,
   [gdprEnabled] [bit] NULL,
   [disableOfferCodeFailureRateLimit] [bit] NOT NULL,
   [wcagToggle] [bit] NULL,
   [did] [bit] NULL,
   [usingDidPool] [bit] NULL,
   [externalId] [varchar](255) NULL,
   [dnisNamedPoolObjectId] [int] NULL
)


GO
