CREATE TABLE [dbo].[_hertzpagesnotinmainbak] (
   [objectId] [int] NOT NULL
      IDENTITY (1,1),
   [organizationObjectId] [int] NULL,
   [showDetail] [bit] NULL,
   [orientation] [int] NULL,
   [hideNoResponsePrompts] [bit] NULL,
   [benchmarkEnabled] [bit] NULL,
   [publicWebAccess] [bit] NOT NULL,
   [folderObjectId] [int] NULL,
   [includeHiddenLocations] [bit] NOT NULL,
   [version] [int] NOT NULL,
   [pageType] [int] NOT NULL,
   [maxGraphsPerPage] [int] NULL,
   [crossTabIndyFieldObjectId] [int] NULL,
   [topLocationPercent] [int] NULL,
   [showScoreWeight] [bit] NULL,
   [showTopLocationPercent] [bit] NULL,
   [trendPeriodObjectId] [int] NULL,
   [groupWidthPercent] [int] NULL,
   [nameObjectId] [int] NOT NULL,
   [descriptionObjectId] [int] NOT NULL,
   [hideLegend] [bit] NULL,
   [showSurveyCount] [bit] NOT NULL,
   [benchmarkObjectId] [int] NULL,
   [jasperReportDefinitionObjectId] [int] NULL,
   [hidden] [bit] NOT NULL,
   [upliftModelObjectId] [int] NULL,
   [periodObjectId] [int] NULL,
   [dashboardDefinitionId] [int] NULL,
   [unstructuredFeedbackObjectId] [int] NULL,
   [editableContentObjectId] [int] NULL,
   [netezzaRunner] [int] NULL,
   [hideEmptyColumns] [bit] NULL,
   [excelTemplateObjectId] [int] NULL,
   [periodCount] [int] NULL,
   [layoutType] [int] NULL,
   [dashboardObjectId] [int] NULL,
   [percentageResponsePrecision] [int] NULL,
   [hideDetailLinks] [bit] NOT NULL,
   [delimiter] [tinyint] NOT NULL,
   [detailLevel] [tinyint] NULL,
   [usePeriodToDateGoal] [tinyint] NOT NULL,
   [benchmarkType] [tinyint] NULL,
   [textAnalyticsCacheEnabled] [tinyint] NOT NULL,
   [brandObjectId] [int] NULL,
   [summaryOption] [tinyint] NULL,
   [aggregationType] [int] NULL,
   [responseCountThreshold] [int] NULL,
   [showPrimaryScore] [tinyint] NULL,
   [ratingView] [bit] NULL,
   [outstandingThreshold] [int] NULL,
   [zeroBased] [bit] NULL,
   [alternateTextFormat] [tinyint] NULL,
   [roundingPlace] [int] NULL,
   [includeZeroResponse] [bit] NOT NULL,
   [showNAForBlankScores] [bit] NOT NULL,
   [benchmarkDepth] [int] NULL,
   [enablePeriodToDate] [bit] NULL,
   [periodToDateColLabelObjectId] [int] NULL,
   [periodToDatePeriodTypeObjectId] [int] NULL,
   [periodToDatePeriodOffset] [int] NULL,
   [periodToDatePeriodCount] [int] NULL,
   [periodToDateCutoffPeriodTypeObjectId] [int] NULL,
   [periodToDateAppendDate] [bit] NULL,
   [privacyFilterEnabled] [tinyint] NULL,
   [thresholdType] [int] NULL,
   [defaultOutputFormatType] [varchar](100) NULL,
   [overrideDataSourceType] [smallint] NULL,
   [disableEDLink] [bit] NULL,
   [includeCriteriaSheet] [bit] NULL,
   [pivotTableName] [nvarchar](50) NULL,
   [excludeTrafficBuildingPlan] [bit] NULL,
   [defaultReportAction] [tinyint] NOT NULL,
   [showResponseCounts] [bit] NOT NULL,
   [userCanOverrideResponseCountThreshold] [bit] NOT NULL
)


GO
