CREATE TABLE [dbo].[_willdf] (
   [objectId] [int] NOT NULL
      IDENTITY (1,1),
   [fieldType] [int] NOT NULL,
   [systemField] [bit] NOT NULL,
   [organizationObjectId] [int] NULL,
   [name] [varchar](50) NOT NULL,
   [readOnly] [bit] NOT NULL,
   [scorePointsPossible] [float] NULL,
   [scoreType] [int] NULL,
   [locationCategoryTypeObjectId] [int] NULL,
   [version] [int] NOT NULL,
   [defaultGoalObjectId] [int] NULL,
   [encrypted] [bit] NULL,
   [enabled] [bit] NULL,
   [scriptBindingName] [varchar](40) NULL,
   [personalInfo] [bit] NOT NULL,
   [labelObjectId] [int] NOT NULL,
   [textObjectId] [int] NOT NULL,
   [formatter] [int] NOT NULL,
   [visibleInDetail] [bit] NOT NULL,
   [encryptiontype] [tinyint] NULL,
   [reversed] [bit] NOT NULL,
   [reportHierarchyMapObjectId] [int] NULL,
   [answerType] [int] NULL,
   [upliftModelObjectId] [int] NULL,
   [optionDisplayMode] [int] NULL,
   [periodObjectId] [int] NULL,
   [ordinalOffset] [int] NULL,
   [definedLength] [int] NULL,
   [entityType] [int] NULL,
   [required] [bit] NULL,
   [scale] [int] NULL,
   [sequence] [int] NULL,
   [standardField] [bit] NULL,
   [showLabel] [bit] NULL,
   [surveyDataFieldId] [int] NULL,
   [userEditable] [bit] NULL,
   [visible] [bit] NULL,
   [purgeSurveyAnswer] [bit] NULL,
   [segmentTypeObjectId] [int] NULL,
   [runtimeComputed] [bit] NULL,
   [computeByRow] [bit] NULL,
   [requireAllComponents] [bit] NULL,
   [externalId] [varchar](255) NULL
)


GO
