SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROC UpdateSurveyResponseStatistics
AS
BEGIN
	UPDATE STATISTICS SurveyResponse WITH FULLSCAN
	UPDATE STATISTICS SurveyResponseAlert WITH FULLSCAN
	UPDATE STATISTICS SurveyResponseAnswer WITH FULLSCAN
	UPDATE STATISTICS SurveyResponseScore WITH FULLSCAN
	UPDATE STATISTICS SurveyResponseState WITH FULLSCAN
	UPDATE STATISTICS SurveyResponseNote WITH FULLSCAN
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
